### ISSUE TITLE
Uncaught exception: Transaction stack size exceeded

### ISSUE THREAD

**Issue by sisou** [nimiq-network/jungle-db#14]
```
Uncaught exception: Transaction stack size exceeded
Uncaught exception: Transaction stack size exceeded Error: Transaction stack size exceeded
    at ObjectStore._commitInternal (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:30214)
    at ObjectStore.commit (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:29614)
    at Transaction._commitBackend (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:42035)
    at Promise.all._transactions.map.e (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:51819)
    at Array.map (<anonymous>)
    at CombinedTransaction._commitBackend (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:51810)
    at CombinedTransaction.commit (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:51367)
    at Function.commitCombined (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:62534)
    at FullChain._extend (/home/users/soeren/github/nimiq-core/dist/node.js:1:126839)
    at <anonymous>
/home/users/soeren/github/nimiq-core/dist/worker-wasm.js:1
(function (exports, require, module, __filename, __dirname) { var Module=function(Module){Module=Module||{};var Module=Module;var Module;if(!Module)Module=eval("(function() { try { return Module || {} } catch(e) { return {} } })()");var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScript

Error: Transaction stack size exceeded
    at ObjectStore._commitInternal (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:30214)
    at ObjectStore.commit (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:29614)
    at Transaction._commitBackend (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:42035)
    at Promise.all._transactions.map.e (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:51819)
    at Array.map (<anonymous>)
    at CombinedTransaction._commitBackend (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:51810)
    at CombinedTransaction.commit (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:51367)
    at Function.commitCombined (/home/users/soeren/github/nimiq-core/node_modules/jungle-db/dist/node.js:1:62534)
    at FullChain._extend (/home/users/soeren/github/nimiq-core/dist/node.js:1:126839)
    at <anonymous>
```

**Comment by paberr** [comment]
You can use version v0.3.7-alpha (just change the tag in the package.json of the Nimiq core) to get some additional logging that might be helpful to trace back this issue.
